services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
      - "50051:50051"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
      - "50052:50051"
    depends_on:
      - mongodb

volumes:
  mongo-data:
