version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service

  inventory-service:
    build:
      context: ./inventory-service
    depends_on:
      - mongodb
      - redis
    ports:
      - "50051:50051"
    environment:
      # Redis settings
      - REDIS_HOSTS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_TLS_ENABLE=false
      - REDIS_DIAL_TIMEOUT=5s
      - REDIS_READ_TIMEOUT=3s
      - REDIS_WRITE_TIMEOUT=3s
      # Cache settings
      - REDIS_CACHE_CLIENT_TTL=12h
      - CLIENT_REFRESH_TIME=1m
      # Mongo settings
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=inventory_db
      - MONGO_TIMEOUT=3s
      # gRPC
      - GRPC_PORT=50051

  order-service:
    build: ./order-service
    ports:
      - "50052:50051"
    depends_on:
      - mongodb

  statistics-service:
    build: ./statistics-service
    ports:
      - "50053:50051"    # host:container
    depends_on:
      - mongodb
      - nats
    environment:
      VERSION:                    "1.0.0"
      # gRPC
      GRPC_PORT:                  "50051"
      GRPC_MAX_MESSAGE_SIZE_MIB:  "12"
      GRPC_MAX_CONNECTION_AGE:    "30s"
      GRPC_MAX_CONNECTION_AGE_GRACE: "10s"
      # Mongo
      MONGO_DB_URI:                 "mongodb:27017"
      MONGO_DB:                     "statistics_db"
      MONGO_USERNAME:               ""           
      MONGO_PWD:                    ""
      MONGO_DB_REPLICA_SET:         ""
      MONGO_WRITE_CONCERN:          "majority"
      MONGO_TLS_FILE_PATH:          ""
      MONGO_TLS_ENABLE:             "false"
      # NATS
      NATS_HOSTS:                 "nats://nats:4222"
      NATS_NKEY:                  "SUACSSL3UAHUDXKFSNVUZRF5UHPMWZ6BFDTJ7M6USDXIEDNPPQYYYCU3VY"
      NATS_IS_TEST:               "true"
      # Subjects
      NATS_ORDER_CREATED_SUBJECT:   "order.created"
      NATS_USER_REGISTERED_SUBJECT: "user.registered"


volumes:
  mongo-data:
