services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "50051:50051"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
    # host:container
      - "50052:50051"
    depends_on:
      - mongodb

  statistics-service:
    build: ./statistics-service
    ports:
      - "50053:50051"
    environment:
      - VERSION=1.0.0
      - GRPC_PORT=50051
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=statistics_db
      - NATS_HOSTS=nats://nats:4222


volumes:
  mongo-data:
